[phases.setup]
nixPkgs = ['python312', 'geos', 'gdal', 'proj', 'postgresql']

[phases.install]
cmds = ['pip install --upgrade pip setuptools wheel', 'pip install -r requirements.txt']

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT'
